version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    networks:
      broker-net:
        ipv4_address: 172.18.0.22

  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - 80:80
  #     - 443:443

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: app_backend
    volumes:
      - ./backend:/app
    networks:
      broker-net:
        ipv4_address: 172.18.0.11

networks:
  broker-net:
    external:
      name: broker