# DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://spring-study.cfhtw7hbyeyq.ap-northeast-2.rds.amazonaws.com:3306/sns?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: melon
    password: ssafymelon


  # jpa settings
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true


  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8081
  servlet:
    context-path: /api

cloud:
  aws:
    credentials:
      accessKey: AKIAI3D44G42RL7HYUOA
      secretKey: 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
    s3:
      bucket: ssafy-sns
    region:
      static: ap-northeast-2
    stack:
      auto: false

