
# DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns?useUnicode=true&characterEncoding=utf8
    username: ssafy
    password: ssafy
#    url: jdbc:mysql://spring-study.cfhtw7hbyeyq.ap-northeast-2.rds.amazonaws.com/melon_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8
#    username: melon
#    password: ssafymelon

  # jpa settings
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

  # oauth
  profiles:
    include: oauth


